EXPORTS["en"] = {
	["press_space"] = "Press Space",
	["cop"] = "Cop",
	["money_to_truck"] = "Put the money in the truck!",
	["get_to_truck"] = "Get to your truck before it leaves!",
	["next_round_begins"] = "Next round begins in",
	["heist"] = "Heist",
	["successful"] = "Successful",
	["failed"] = "Failed",
	["best_crew"] = "Best Crew",
	["most_bags_collected"] = "Most Bags Collected",
	["most_money"] = "Most Money",
	["most_kills"] = "Most Kills",
	["most_knockouts"] = "Most Knockouts",

	["select_loadout"] = "Select Your Loadout",
	["robbing_bank_in"] = "Robbing bank in",
	["store"] = "Store",
	["buy"] = "Buy",
	["you"] = "You",
	["empty_inv"] = "You don't have anything in your inventory.",
	["primary"] = "Primary",
	["secondary"] = "Secondary",
	["you_have"] = "You have",
	["join"] = "Join",
	["members"] = "members",
	["your_team"] = "Your Team",
	["other_teams"] = "Other Teams",
	["a_moment"] = "a moment",

	["team_rebalance_1"] = "Teams have been rebalanced. You have joined the",
	["team"] = "team",
	["joined_team"] = "You have joined the",
};
